### ISSUE TITLE
Option to use line number instead of regex

### ISSUE THREAD

**Issue by Linuus** [arthurnn/minitest-emacs#50]
Hi!

Is it possible to use line numbers instead of regex to execute the test(s)? In rails, you can run `rails test test/foo/bar.rb:21` for instance. It's a bit more reliable than the current regex which fails quite often for me.

Perhaps this can be the default when setting the `minitest-use-rails` to `t`?

**Comment by gcentauri** [comment]
Thanks for creating an issue!  I was just thinking about switching to line numbers instead of regex. It should be quite easy to change the code here https://github.com/arthurnn/minitest-emacs/blob/de1c0b84b93966e1b93d55ff8dbff6bd88e5c29b/minitest.el#L143

This currently returns the location of the point and the regex match of the test name. If minitest supports providing line numbers for single tests across the board, I'm not sure if there is any particular benefit to using regex anyway.

I can probably work on this within a week or so, but if you want to give it a shot I certainly don't mind a hand :)

**Comment by Linuus** [comment]
I think the line number support is a Rails specific thing.

**Comment by gcentauri** [comment]
Do you mind specifying when it is that you get failures on tests?

I have a PR where I noticed test names starting with `#` would not get picked up properly, and I've also noticed `it { ...}` tests are not picked up either.  I will look into using line numbers for rails, as that is certainly easier there, but it would be nice to have it working for non-rails ruby projects too.

**Comment by Linuus** [comment]
Sure!

1. I've noticed the `#` issue as well.
2. When I have parentheses `test("my test")`
3. Nested contexts:

```ruby
describe("something") do
  test("foobar") do
  end
end

describe("something else") do
  test("foobar") do
  end
end
```

With point at the first foobar test, it will run `... -n /foobar/` which runs both test cases.

Not sure if the last one is fixable (besides line numbers in rails) but still kind of an issue... :)

**Comment by gcentauri** [comment]
Thanks!  I'll work on this, I appreciate the input.

**Comment by gcentauri** [comment]
@Linuus - I just pushed a change to use line numbers if `minitest-use-rails` is true. Let me know if you notice any other issues after you update your package!

**Comment by gcentauri** [comment]
@Linuus - i've been using the line numbers with `minitest-use-rails t` for the past week, and it seems good as far as I can tell. I'm going to close this issue, but I'll reopen if something isn't working for you. I hope to address some of the other issues you reported with the non-rails code as well.
